// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/sashabaranov/testbackend/proto/backend.proto

package backend

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Animal struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	PhotoUrl             string   `protobuf:"bytes,4,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Animal) Reset()         { *m = Animal{} }
func (m *Animal) String() string { return proto.CompactTextString(m) }
func (*Animal) ProtoMessage()    {}
func (*Animal) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7dbe1d61ff0250, []int{0}
}

func (m *Animal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Animal.Unmarshal(m, b)
}
func (m *Animal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Animal.Marshal(b, m, deterministic)
}
func (m *Animal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Animal.Merge(m, src)
}
func (m *Animal) XXX_Size() int {
	return xxx_messageInfo_Animal.Size(m)
}
func (m *Animal) XXX_DiscardUnknown() {
	xxx_messageInfo_Animal.DiscardUnknown(m)
}

var xxx_messageInfo_Animal proto.InternalMessageInfo

func (m *Animal) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Animal) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Animal) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Animal) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

type CreateAnimalRequest struct {
	Animal               *Animal  `protobuf:"bytes,1,opt,name=animal,proto3" json:"animal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAnimalRequest) Reset()         { *m = CreateAnimalRequest{} }
func (m *CreateAnimalRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAnimalRequest) ProtoMessage()    {}
func (*CreateAnimalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7dbe1d61ff0250, []int{1}
}

func (m *CreateAnimalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAnimalRequest.Unmarshal(m, b)
}
func (m *CreateAnimalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAnimalRequest.Marshal(b, m, deterministic)
}
func (m *CreateAnimalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAnimalRequest.Merge(m, src)
}
func (m *CreateAnimalRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAnimalRequest.Size(m)
}
func (m *CreateAnimalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAnimalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAnimalRequest proto.InternalMessageInfo

func (m *CreateAnimalRequest) GetAnimal() *Animal {
	if m != nil {
		return m.Animal
	}
	return nil
}

type CreateAnimalResponse struct {
	Created              *Animal  `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAnimalResponse) Reset()         { *m = CreateAnimalResponse{} }
func (m *CreateAnimalResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAnimalResponse) ProtoMessage()    {}
func (*CreateAnimalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7dbe1d61ff0250, []int{2}
}

func (m *CreateAnimalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAnimalResponse.Unmarshal(m, b)
}
func (m *CreateAnimalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAnimalResponse.Marshal(b, m, deterministic)
}
func (m *CreateAnimalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAnimalResponse.Merge(m, src)
}
func (m *CreateAnimalResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAnimalResponse.Size(m)
}
func (m *CreateAnimalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAnimalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAnimalResponse proto.InternalMessageInfo

func (m *CreateAnimalResponse) GetCreated() *Animal {
	if m != nil {
		return m.Created
	}
	return nil
}

type GetAnimalRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAnimalRequest) Reset()         { *m = GetAnimalRequest{} }
func (m *GetAnimalRequest) String() string { return proto.CompactTextString(m) }
func (*GetAnimalRequest) ProtoMessage()    {}
func (*GetAnimalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7dbe1d61ff0250, []int{3}
}

func (m *GetAnimalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnimalRequest.Unmarshal(m, b)
}
func (m *GetAnimalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnimalRequest.Marshal(b, m, deterministic)
}
func (m *GetAnimalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnimalRequest.Merge(m, src)
}
func (m *GetAnimalRequest) XXX_Size() int {
	return xxx_messageInfo_GetAnimalRequest.Size(m)
}
func (m *GetAnimalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnimalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnimalRequest proto.InternalMessageInfo

func (m *GetAnimalRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetAnimalResponse struct {
	Animal               *Animal  `protobuf:"bytes,1,opt,name=animal,proto3" json:"animal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAnimalResponse) Reset()         { *m = GetAnimalResponse{} }
func (m *GetAnimalResponse) String() string { return proto.CompactTextString(m) }
func (*GetAnimalResponse) ProtoMessage()    {}
func (*GetAnimalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7dbe1d61ff0250, []int{4}
}

func (m *GetAnimalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnimalResponse.Unmarshal(m, b)
}
func (m *GetAnimalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnimalResponse.Marshal(b, m, deterministic)
}
func (m *GetAnimalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnimalResponse.Merge(m, src)
}
func (m *GetAnimalResponse) XXX_Size() int {
	return xxx_messageInfo_GetAnimalResponse.Size(m)
}
func (m *GetAnimalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnimalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnimalResponse proto.InternalMessageInfo

func (m *GetAnimalResponse) GetAnimal() *Animal {
	if m != nil {
		return m.Animal
	}
	return nil
}

type UpdateAnimalRequest struct {
	Updated              *Animal  `protobuf:"bytes,1,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAnimalRequest) Reset()         { *m = UpdateAnimalRequest{} }
func (m *UpdateAnimalRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAnimalRequest) ProtoMessage()    {}
func (*UpdateAnimalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7dbe1d61ff0250, []int{5}
}

func (m *UpdateAnimalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAnimalRequest.Unmarshal(m, b)
}
func (m *UpdateAnimalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAnimalRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAnimalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAnimalRequest.Merge(m, src)
}
func (m *UpdateAnimalRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAnimalRequest.Size(m)
}
func (m *UpdateAnimalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAnimalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAnimalRequest proto.InternalMessageInfo

func (m *UpdateAnimalRequest) GetUpdated() *Animal {
	if m != nil {
		return m.Updated
	}
	return nil
}

type UpdateAnimalResponse struct {
	Result               *Animal  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAnimalResponse) Reset()         { *m = UpdateAnimalResponse{} }
func (m *UpdateAnimalResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAnimalResponse) ProtoMessage()    {}
func (*UpdateAnimalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7dbe1d61ff0250, []int{6}
}

func (m *UpdateAnimalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAnimalResponse.Unmarshal(m, b)
}
func (m *UpdateAnimalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAnimalResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAnimalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAnimalResponse.Merge(m, src)
}
func (m *UpdateAnimalResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAnimalResponse.Size(m)
}
func (m *UpdateAnimalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAnimalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAnimalResponse proto.InternalMessageInfo

func (m *UpdateAnimalResponse) GetResult() *Animal {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteAnimalRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAnimalRequest) Reset()         { *m = DeleteAnimalRequest{} }
func (m *DeleteAnimalRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAnimalRequest) ProtoMessage()    {}
func (*DeleteAnimalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7dbe1d61ff0250, []int{7}
}

func (m *DeleteAnimalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAnimalRequest.Unmarshal(m, b)
}
func (m *DeleteAnimalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAnimalRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAnimalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAnimalRequest.Merge(m, src)
}
func (m *DeleteAnimalRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAnimalRequest.Size(m)
}
func (m *DeleteAnimalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAnimalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAnimalRequest proto.InternalMessageInfo

func (m *DeleteAnimalRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteAnimalResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAnimalResponse) Reset()         { *m = DeleteAnimalResponse{} }
func (m *DeleteAnimalResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAnimalResponse) ProtoMessage()    {}
func (*DeleteAnimalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7dbe1d61ff0250, []int{8}
}

func (m *DeleteAnimalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAnimalResponse.Unmarshal(m, b)
}
func (m *DeleteAnimalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAnimalResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAnimalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAnimalResponse.Merge(m, src)
}
func (m *DeleteAnimalResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAnimalResponse.Size(m)
}
func (m *DeleteAnimalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAnimalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAnimalResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Animal)(nil), "backend.Animal")
	proto.RegisterType((*CreateAnimalRequest)(nil), "backend.CreateAnimalRequest")
	proto.RegisterType((*CreateAnimalResponse)(nil), "backend.CreateAnimalResponse")
	proto.RegisterType((*GetAnimalRequest)(nil), "backend.GetAnimalRequest")
	proto.RegisterType((*GetAnimalResponse)(nil), "backend.GetAnimalResponse")
	proto.RegisterType((*UpdateAnimalRequest)(nil), "backend.UpdateAnimalRequest")
	proto.RegisterType((*UpdateAnimalResponse)(nil), "backend.UpdateAnimalResponse")
	proto.RegisterType((*DeleteAnimalRequest)(nil), "backend.DeleteAnimalRequest")
	proto.RegisterType((*DeleteAnimalResponse)(nil), "backend.DeleteAnimalResponse")
}

func init() {
	proto.RegisterFile("github.com/sashabaranov/testbackend/proto/backend.proto", fileDescriptor_8f7dbe1d61ff0250)
}

var fileDescriptor_8f7dbe1d61ff0250 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x41, 0x4f, 0xb3, 0x40,
	0x14, 0x0c, 0xb4, 0x5f, 0xf9, 0x78, 0xad, 0x5a, 0xb7, 0x8d, 0xc1, 0xaa, 0x49, 0xb3, 0x89, 0xb1,
	0xbd, 0x40, 0x52, 0x0f, 0x1e, 0x34, 0x6a, 0xab, 0x89, 0x87, 0xde, 0x48, 0x7a, 0xd1, 0x83, 0x59,
	0xca, 0xa6, 0x25, 0x52, 0x40, 0x76, 0xf1, 0x97, 0xf9, 0x03, 0x8d, 0xcb, 0xb6, 0x2e, 0x08, 0x89,
	0xb7, 0xdd, 0x37, 0xc3, 0xcc, 0xbc, 0xd9, 0x00, 0x57, 0xab, 0x80, 0xaf, 0x33, 0xcf, 0x5e, 0xc6,
	0x1b, 0x87, 0x11, 0xb6, 0x26, 0x1e, 0x49, 0x49, 0x14, 0x7f, 0x38, 0x9c, 0x32, 0xee, 0x91, 0xe5,
	0x1b, 0x8d, 0x7c, 0x27, 0x49, 0x63, 0x1e, 0x3b, 0xf2, 0x66, 0x8b, 0x1b, 0x32, 0xe4, 0x15, 0xbf,
	0x40, 0x6b, 0x1a, 0x05, 0x1b, 0x12, 0xa2, 0x7d, 0xd0, 0x03, 0xdf, 0xd2, 0x86, 0xda, 0x68, 0xcf,
	0xd5, 0x03, 0x1f, 0x21, 0x68, 0x46, 0x64, 0x43, 0x2d, 0x7d, 0xa8, 0x8d, 0x4c, 0x57, 0x9c, 0x51,
	0x17, 0x1a, 0x64, 0x45, 0xad, 0xc6, 0x50, 0x1b, 0xfd, 0x73, 0xbf, 0x8f, 0xe8, 0x04, 0xcc, 0x64,
	0x1d, 0xf3, 0xf8, 0x35, 0x4b, 0x43, 0xab, 0x29, 0xa8, 0xff, 0xc5, 0x60, 0x91, 0x86, 0xf8, 0x16,
	0x7a, 0x0f, 0x29, 0x25, 0x9c, 0xe6, 0x16, 0x2e, 0x7d, 0xcf, 0x28, 0xe3, 0xe8, 0x02, 0x5a, 0x44,
	0x0c, 0x84, 0x5b, 0x7b, 0x72, 0x60, 0x6f, 0xc3, 0x49, 0x9e, 0x84, 0xf1, 0x14, 0xfa, 0xc5, 0xef,
	0x59, 0x12, 0x47, 0x8c, 0xa2, 0x31, 0x18, 0x4b, 0x31, 0xf7, 0xeb, 0x14, 0xb6, 0x38, 0xc6, 0xd0,
	0x7d, 0xa2, 0xbc, 0xe8, 0x5f, 0xda, 0x14, 0xdf, 0xc0, 0xa1, 0xc2, 0x91, 0x1e, 0x7f, 0x0e, 0x79,
	0x0f, 0xbd, 0x45, 0xe2, 0xff, 0x5a, 0x72, 0x0c, 0x46, 0x26, 0xc6, 0xf5, 0x19, 0x25, 0x8e, 0xef,
	0xa0, 0x5f, 0x54, 0xf8, 0x89, 0x90, 0x52, 0x96, 0x85, 0xbc, 0x36, 0x42, 0x0e, 0xe3, 0x73, 0xe8,
	0x3d, 0xd2, 0x90, 0x96, 0x23, 0x94, 0xf7, 0x3c, 0x82, 0x7e, 0x91, 0x96, 0xfb, 0x4c, 0x3e, 0x75,
	0x30, 0x66, 0xb9, 0x32, 0x9a, 0x43, 0x47, 0xad, 0x1c, 0x9d, 0xee, 0x3c, 0x2b, 0x5e, 0x72, 0x70,
	0x56, 0x83, 0xca, 0x05, 0x66, 0x60, 0xee, 0x8a, 0x45, 0xc7, 0x3b, 0x6e, 0xf9, 0x41, 0x06, 0x83,
	0x2a, 0x48, 0x6a, 0xcc, 0xa1, 0xa3, 0x96, 0xa3, 0x04, 0xaa, 0x68, 0x5d, 0x09, 0x54, 0xd9, 0xe8,
	0x1c, 0x3a, 0x6a, 0x03, 0x8a, 0x58, 0x45, 0x7f, 0x8a, 0x58, 0x55, 0x6d, 0xb3, 0xf6, 0xb3, 0x69,
	0x5f, 0x4b, 0x86, 0xd7, 0x12, 0xff, 0xd5, 0xe5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x84, 0x3e,
	0x1a, 0x43, 0x92, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BackendClient is the client API for Backend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BackendClient interface {
	CreateAnimal(ctx context.Context, in *CreateAnimalRequest, opts ...grpc.CallOption) (*CreateAnimalResponse, error)
	GetAnimal(ctx context.Context, in *GetAnimalRequest, opts ...grpc.CallOption) (*GetAnimalResponse, error)
	UpdateAnimal(ctx context.Context, in *UpdateAnimalRequest, opts ...grpc.CallOption) (*UpdateAnimalResponse, error)
	DeleteAnimal(ctx context.Context, in *DeleteAnimalRequest, opts ...grpc.CallOption) (*DeleteAnimalResponse, error)
}

type backendClient struct {
	cc *grpc.ClientConn
}

func NewBackendClient(cc *grpc.ClientConn) BackendClient {
	return &backendClient{cc}
}

func (c *backendClient) CreateAnimal(ctx context.Context, in *CreateAnimalRequest, opts ...grpc.CallOption) (*CreateAnimalResponse, error) {
	out := new(CreateAnimalResponse)
	err := c.cc.Invoke(ctx, "/backend.Backend/CreateAnimal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetAnimal(ctx context.Context, in *GetAnimalRequest, opts ...grpc.CallOption) (*GetAnimalResponse, error) {
	out := new(GetAnimalResponse)
	err := c.cc.Invoke(ctx, "/backend.Backend/GetAnimal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) UpdateAnimal(ctx context.Context, in *UpdateAnimalRequest, opts ...grpc.CallOption) (*UpdateAnimalResponse, error) {
	out := new(UpdateAnimalResponse)
	err := c.cc.Invoke(ctx, "/backend.Backend/UpdateAnimal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) DeleteAnimal(ctx context.Context, in *DeleteAnimalRequest, opts ...grpc.CallOption) (*DeleteAnimalResponse, error) {
	out := new(DeleteAnimalResponse)
	err := c.cc.Invoke(ctx, "/backend.Backend/DeleteAnimal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendServer is the server API for Backend service.
type BackendServer interface {
	CreateAnimal(context.Context, *CreateAnimalRequest) (*CreateAnimalResponse, error)
	GetAnimal(context.Context, *GetAnimalRequest) (*GetAnimalResponse, error)
	UpdateAnimal(context.Context, *UpdateAnimalRequest) (*UpdateAnimalResponse, error)
	DeleteAnimal(context.Context, *DeleteAnimalRequest) (*DeleteAnimalResponse, error)
}

// UnimplementedBackendServer can be embedded to have forward compatible implementations.
type UnimplementedBackendServer struct {
}

func (*UnimplementedBackendServer) CreateAnimal(ctx context.Context, req *CreateAnimalRequest) (*CreateAnimalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAnimal not implemented")
}
func (*UnimplementedBackendServer) GetAnimal(ctx context.Context, req *GetAnimalRequest) (*GetAnimalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnimal not implemented")
}
func (*UnimplementedBackendServer) UpdateAnimal(ctx context.Context, req *UpdateAnimalRequest) (*UpdateAnimalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAnimal not implemented")
}
func (*UnimplementedBackendServer) DeleteAnimal(ctx context.Context, req *DeleteAnimalRequest) (*DeleteAnimalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAnimal not implemented")
}

func RegisterBackendServer(s *grpc.Server, srv BackendServer) {
	s.RegisterService(&_Backend_serviceDesc, srv)
}

func _Backend_CreateAnimal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAnimalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).CreateAnimal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Backend/CreateAnimal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).CreateAnimal(ctx, req.(*CreateAnimalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetAnimal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnimalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetAnimal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Backend/GetAnimal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetAnimal(ctx, req.(*GetAnimalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_UpdateAnimal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAnimalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).UpdateAnimal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Backend/UpdateAnimal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).UpdateAnimal(ctx, req.(*UpdateAnimalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_DeleteAnimal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAnimalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).DeleteAnimal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Backend/DeleteAnimal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).DeleteAnimal(ctx, req.(*DeleteAnimalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Backend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "backend.Backend",
	HandlerType: (*BackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAnimal",
			Handler:    _Backend_CreateAnimal_Handler,
		},
		{
			MethodName: "GetAnimal",
			Handler:    _Backend_GetAnimal_Handler,
		},
		{
			MethodName: "UpdateAnimal",
			Handler:    _Backend_UpdateAnimal_Handler,
		},
		{
			MethodName: "DeleteAnimal",
			Handler:    _Backend_DeleteAnimal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/sashabaranov/testbackend/proto/backend.proto",
}
